steps:
  - name: 'python'
    id: run
    entrypoint: /bin/sh
    args:
    - -c
    - "pip install -r requirements.txt && python pipeline/pipeline_publisher.py \
	&& python pipeline/pipeline_run.py && file.sh"
    
    